FROM --platform=linux/amd64 ubuntu:22.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y automake pkg-config libtool build-essential libext2fs-dev libz-dev libssl-dev

COPY . /repo
WORKDIR /repo
RUN autoreconf -if
RUN ./configure
RUN make -j8
